# Configuración para el perfil SUPABASE
spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=${SUPABASE_USER}
spring.datasource.password=${SUPABASE_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Optimizado para Supabase
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.flyway.locations=classpath:db/migration/postgresql
