#spring.datasource.url=jdbc:postgresql://fichapp.duckdns.org:5432/Fichapp
#spring.datasource.username=Fichapp
#spring.datasource.password=Fichapp_ue
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.flyway.enabled=false
