spring.application.name=fichApp-api
spring.flyway.enabled=true

# Perfil Local por defecto
spring.profiles.active=server

# JPA/Hibernate Configuración general
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Subida Archivos (Resolviendo HTTP 413 Payload Too Large)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Mostrar mensajes de error detallados
server.error.include-message=always
server.error.include-exception=true
