spring.application.name=fichApp-api
spring.flyway.enabled=false
# Eliminar desde aqui -- Conf de conexión a adminer
# PostgreSQL Remote Database Configuration
spring.datasource.url=jdbc:postgresql://79.72.53.251:5432/Fichapp
spring.datasource.username=Fichapp
spring.datasource.password=Fichapp_ue
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false



