spring.application.name=fichApp-api
spring.flyway.enabled=true

# Default Profile - Local por defecto
spring.profiles.active=server

# JPA/Hibernate Common Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



